[package]
name = "technical_analysis"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
rust_decimal = { version = "1.35", features = ["maths"], optional = true }
pyo3   = { version = "0.22.6", optional = true, features = ["extension-module", "abi3-py39"] }
numpy  = { version = "0.22",   optional = true }

[dev-dependencies]

[features]
default = []
precision = ["rust_decimal"]
unsafe = []
python = ["dep:pyo3", "dep:numpy"]
