from __future__ import annotations

import numpy as np

_Array  = np.ndarray  # dtype=float64, shape=(n,)
_Array2 = tuple[np.ndarray, np.ndarray]
_Array3 = tuple[np.ndarray, np.ndarray, np.ndarray]

class SimpleMovingAverage:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class ExponentialMovingAverage:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def set_ema(self, value: float) -> None: ...
    def __repr__(self) -> str: ...

class SimpleMovingMedian:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class RelativeStrengthIndex:
    def __init__(self, period: int = 14) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class StandardDeviation:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class MeanAbsDev:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class MedianAbsoluteStandardDeviation:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class RateOfChange:
    def __init__(self, period: int = 12) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class ChandeMomentumOscillator:
    def __init__(self, period: int = 14) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class High:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class Low:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> float | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class HighLow:
    """(high, low)"""
    def __init__(self, period: int = 20) -> None: ...
    def next(self, value: float) -> tuple[float, float] | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array2: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class BollingerBands:
    """(upper, middle, lower)"""
    def __init__(self, period: int = 20, multiplier: float = 2.0) -> None: ...
    def next(self, value: float) -> tuple[float, float, float] | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array3: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class MovingAverageConvergenceDivergence:
    """(macd, signal, histogram)"""
    def __init__(
        self,
        short_period: int = 12,
        long_period: int = 26,
        signal_period: int = 9,
    ) -> None: ...
    def next(self, value: float) -> tuple[float, float, float] | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array3: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class PercentagePriceOscillator:
    """(ppo, signal, histogram)"""
    def __init__(
        self,
        short_period: int = 12,
        long_period: int = 26,
        signal_period: int = 9,
    ) -> None: ...
    def next(self, value: float) -> tuple[float, float, float] | None: ...
    def next_chunk(self, value: np.ndarray) -> _Array3: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class Aroon:
    """(aroon_up, aroon_down)"""
    def __init__(self, period: int = 14) -> None: ...
    def next(self, high: float, low: float) -> tuple[float, float] | None: ...
    def next_chunk(self, high: np.ndarray, low: np.ndarray) -> _Array2: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class StochasticOscillator:
    """(%K, %D)"""
    def __init__(self, period: int = 14, d_period: int = 3) -> None: ...
    def next(self, high: float, low: float, close: float) -> tuple[float, float] | None: ...
    def next_chunk(
        self,
        high: np.ndarray,
        low: np.ndarray,
        close: np.ndarray,
    ) -> _Array2: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class DonchianChannels:
    """(upper, middle, lower)"""
    def __init__(self, period: int = 20) -> None: ...
    def next(self, high: float, low: float) -> tuple[float, float, float] | None: ...
    def next_chunk(self, high: np.ndarray, low: np.ndarray) -> _Array3: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class KeltnerChannels:
    """(upper, middle, lower)"""
    def __init__(
        self, ema_period: int = 20, atr_period: int = 10, multiplier: float = 2.0
    ) -> None: ...
    def next(
        self, high: float, low: float, close: float
    ) -> tuple[float, float, float] | None: ...
    def next_chunk(
        self,
        high: np.ndarray,
        low: np.ndarray,
        close: np.ndarray,
    ) -> _Array3: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class AverageTrueRange:
    def __init__(self, period: int = 14) -> None: ...
    def next(self, high: float, low: float, close: float) -> float | None: ...
    def next_chunk(
        self,
        high: np.ndarray,
        low: np.ndarray,
        close: np.ndarray,
    ) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class CommodityChannelIndex:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, high: float, low: float, close: float) -> float | None: ...
    def next_chunk(
        self,
        high: np.ndarray,
        low: np.ndarray,
        close: np.ndarray,
    ) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class ChaikinMoneyFlow:
    def __init__(self, period: int = 20) -> None: ...
    def next(self, high: float, low: float, close: float, volume: float) -> float | None: ...
    def next_chunk(
        self,
        high: np.ndarray,
        low: np.ndarray,
        close: np.ndarray,
        volume: np.ndarray,
    ) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class ParabolicSAR:
    def __init__(
        self,
        acceleration_factor: float = 0.02,
        max_acceleration_factor: float = 0.2,
        initialization_period: int = 5,
    ) -> None: ...
    def next(self, high: float, low: float) -> float | None: ...
    def next_chunk(self, high: np.ndarray, low: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class OnBalanceVolume:
    def __init__(self) -> None: ...
    def next(self, close: float, volume: float) -> float: ...
    def next_chunk(self, close: np.ndarray, volume: np.ndarray) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...

class VolumeWeightedAveragePrice:
    """Call reset() between sessions."""
    def __init__(self) -> None: ...
    def next(self, high: float, low: float, close: float, volume: float) -> float: ...
    def next_chunk(
        self,
        high: np.ndarray,
        low: np.ndarray,
        close: np.ndarray,
        volume: np.ndarray,
    ) -> _Array: ...
    def reset(self) -> None: ...
    def __repr__(self) -> str: ...
